version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "torque-team"
    assignees:
      - "torque-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore major version updates for core dependencies
      - dependency-name: "@types/vscode"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]